Added GPTQ converter functionality to the script
llm-jp/llm-jp-sft pull request #37
Opened 2024-01-29 12:30 UTC by wangqihanginthesky

モデルをGPTQに変換するscriptを追加しました。

2024-02-12 23:47 UTC, wangqihanginthesky commented
gptqに関しては 評価の部分は従来と同じ方法で モデルを指定すればできるので、特にllm-evalの部分に追加を入れていません。

2024-02-13 05:10 UTC, hiroshi-matsuda-rit commented
確認しますが、少し時間をください🙌

2024-02-22 23:03 UTC, hiroshi-matsuda-rit requested changes
@wangqihanginthesky レビューが遅くなり申し訳ありません。いくつかコメントしたので対応をお願いします。

2024-02-22 23:03 UTC, hiroshi-matsuda-rit commented on converter/gptq_converter.py
> +    # inference check
こういうテストは大事だと思います。
一方で単純にocnversionだけを実行する必要がある場合も想定する必要があるので、次のいずれかの対応をお願いできますか？
- デフォルトでテストを実行し、`--silent`オプションが指定されたらテストをスキップする
- `--test`オプションが指定された場合のみテストを実行する

2024-03-03 03:25 UTC, wangqihanginthesky commented on converter/gptq_converter.py
> +    # inference check
--testオプションが指定された場合のみテストを実行する
ありがとうございます。で対応します。

2024-03-03 03:26 UTC, wangqihanginthesky commented on converter/gptq_converter.py
> +    args = arg_parser.parse_args()
ありがとうございます。デフォルト値設定で対応しました。

2024-03-03 03:26 UTC, wangqihanginthesky commented on requirements.in
> +auto-gptq==0.6.0
ありがどうございます。auto-gptq>=0.6.0　で対応しました。

2024-03-10 06:47 UTC, wangqihanginthesky commented
@hiroshi-matsuda-rit ほか問題なければマージしたいのですが、よろしいでしょうか。

2024-03-10 10:57 UTC, hiroshi-matsuda-rit requested changes
--bitsを4または8のchoiceにしていただいたうえで、マージをお願いします！

2024-03-10 10:57 UTC, hiroshi-matsuda-rit commented on converter/gptq_converter.py
> +    arg_parser.add_argument("--bits", type=int, default=4, help="quantization bits")
bitsはchoiceにできますか？

2024-03-11 11:15 UTC, wangqihanginthesky commented on converter/gptq_converter.py
> +    arg_parser.add_argument("--bits", type=int, default=4, help="quantization bits")
@hiroshi-matsuda-rit 修正しました。

2024-03-18 06:59 UTC, wangqihanginthesky commented
@hiroshi-matsuda-rit ほか問題なければマージしたいのですが、よろしいでしょうか。🙇

2024-03-18 19:01 UTC, merged

2024-03-18 19:02 UTC, hiroshi-matsuda-rit commented
対応いただき有難うございました。 @wangqihanginthesky